// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgnPAj-w5ICjOjdd2MtfWN0KxmFzbgvaY',
    appId: '1:373987499196:web:2802559309600d0c47c4b9',
    messagingSenderId: '373987499196',
    projectId: 'head-sense-1111',
    authDomain: 'head-sense-1111.firebaseapp.com',
    storageBucket: 'head-sense-1111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4RiHJhgY_FBf2ZGanYUPqlYCQ6HNTrA',
    appId: '1:373987499196:android:6894db5a8c95266c47c4b9',
    messagingSenderId: '373987499196',
    projectId: 'head-sense-1111',
    storageBucket: 'head-sense-1111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPS2VCW8b1XJjOq_WsDBsEIuSwuJnxgHI',
    appId: '1:373987499196:ios:c5d1beaf27fc2c9747c4b9',
    messagingSenderId: '373987499196',
    projectId: 'head-sense-1111',
    storageBucket: 'head-sense-1111.firebasestorage.app',
    androidClientId: '373987499196-4d7dom2mn76l4n00pjh26rl8uv3q7e7f.apps.googleusercontent.com',
    iosClientId: '373987499196-1g1rc5grc321hjhls07k7jskorvgut0n.apps.googleusercontent.com',
    iosBundleId: 'com.picklelabs.somatica',
  );
}
